[package]
name = "lite-inf"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
candle-core = "0.7.2"
candle-transformers = "0.7.2"
clap = { version = "4.5.20", features = ["derive"] }
hf-hub = "0.3.2"
serde = "1.0.210"
serde_json = "1.0.131"
